# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam3app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25)),
                ('tasks', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apointments', to='exam3app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='poster',
        ),
        migrations.DeleteModel(
            name='Quotes',
        ),
    ]
